services:
  ashora:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/ashora
      - ashora_static_volume:/ashora/static
      - ashora_file_volume:/ashora/files
    restart: always
    ports:
      - "8000:8000"
    networks:
      - ashora_network
      - nginx-network
    depends_on:
      - ashora_postgresql
  ashora_postgresql:
    image: postgres:latest
    container_name: ashora_postgresql
    volumes:
      - ashora_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - ashora_network

volumes:
  ashora_postgresql:
    external: true
  ashora_static_volume:
    external: true
  ashora_file_volume:
    external: true
networks:
  ashora_network:
    external: true
  nginx-network:
    external: true