# Generated by Django 5.2 on 2025-06-17 13:24

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='promote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.FileField(upload_to='files/article_cover/', validators=[blog.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.FileField(upload_to='files/category_cover/', validators=[blog.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(upload_to='files/user_avatar/', validators=[blog.models.validate_file_extension]),
        ),
    ]
